#!/bin/bash
#SBATCH --job-name=job_wrf
#SBATCH --dependency=afterok:
#SBATCH -p radclouds
#SBATCH -N 6
#SBATCH -n 336
#SBATCH --nodelist=c793,c795,c798,c799,c855,c875
#SBATCH --exclusive
#SBATCH --output=outbatch.out%j.txt
#SBATCH --error=outbatch.err%j.txt
#SBATCH -t 60:00:00 # max job run time HH:MM:SS

module purge
source bashrc_wrf

echo "+:h:0:RTHRATSW,RTHRATLW,RTHRATSWC,RTHRATLWC,H_DIABATIC" > var_extra_output

mpirun ./wrf.exe

mv $1 $2	# Move the wrfoutfiles to the specific directories