#!/bin/bash
#SBATCH --job-name=job_real
#SBATCH --dependency=afterok:17468405
#SBATCH -p radclouds
#SBATCH -N 1
#SBATCH -n 56
#SBATCH --nodelist=c795
#SBATCH --exclusive
#SBATCH --output=outbatch.out%j.txt
#SBATCH --error=outbatch.err%j.txt
#SBATCH -t 24:00:00 # max job run time HH:MM:SS

# Updates namelist.input in the WRF/run directory ($2),
	# with the one made in the data storage directory ($1)
cp $1 $2	# Update the namelist.input

module purge
source bashrc_wrf

mpirun ./real.exe